#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// --- Audio: INMP441 microphone + MAX98357A amplifier ---
// BCLK and WS are shared by both devices.
#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_4  // INMP441 SCK / MAX98357A BCLK
#define AUDIO_I2S_GPIO_WS GPIO_NUM_5    // INMP441 WS / MAX98357A LRC
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_6   // INMP441 SD -> ESP32
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7  // ESP32 -> MAX98357A DIN

// --- Buttons and LED ---
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define BUILTIN_LED_GPIO GPIO_NUM_48

// --- 2.8-inch ILI9341 SPI display ---
#define DISPLAY_MOSI_PIN GPIO_NUM_11
#define DISPLAY_CLK_PIN GPIO_NUM_12
#define DISPLAY_CS_PIN GPIO_NUM_10
#define DISPLAY_DC_PIN GPIO_NUM_9
#define DISPLAY_RST_PIN GPIO_NUM_14
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_13

// Start false. Change to true if the display/backlight behaves inverted.
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define LCD_TYPE_ILI9341_SERIAL

#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 320

#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false

#define DISPLAY_INVERT_COLOR false
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_SPI_MODE 0

#endif  // _BOARD_CONFIG_H_