#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// --- Audio (e.g. INMP441 Mic + MAX98357A Amp) ---
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_4
#define AUDIO_I2S_GPIO_WS GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_6   // Mic DATA
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7  // Amp DIN
// --- Audio (INMP441 Mic + MAX98357A Amp) ---
// BCLK and WS are shared between INMP441 and MAX98357A
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_4  // Shared: INMP441 SCK & MAX98357A BCLK
#define AUDIO_I2S_GPIO_WS GPIO_NUM_5    // Shared: INMP441 WS & MAX98357A LRC
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_6   // Mic: INMP441 SD (Data In to ESP32)
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7  // Amp: MAX98357A DIN (Data Out from ESP32)

// --- Buttons & LED ---
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define BUILTIN_LED_GPIO GPIO_NUM_48

// --- ILI9341 2.4" Display (SPI) ---
// --- ILI9341 2.8" Display (SPI) ---
#define DISPLAY_MOSI_PIN GPIO_NUM_11
#define DISPLAY_CLK_PIN GPIO_NUM_12
#define DISPLAY_CS_PIN GPIO_NUM_10
#define DISPLAY_DC_PIN GPIO_NUM_9
#define DISPLAY_RST_PIN GPIO_NUM_14
#define DISPLAY_CLK_PIN GPIO_NUM_12
#define DISPLAY_CS_PIN GPIO_NUM_10
#define DISPLAY_DC_PIN GPIO_NUM_9
#define DISPLAY_RST_PIN GPIO_NUM_14
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_13

#define LCD_TYPE_ILI9341_SERIAL
#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 320
#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 320
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR true
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_SPI_MODE 0

#endif
#endif  // _BOARD_CONFIG_H_